# Generated by Django 5.0.1 on 2024-01-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("phone", models.BigIntegerField(max_length=20)),
                ("email", models.CharField(max_length=30)),
                ("datecheckin", models.DateField(max_length=10)),
                ("datecheckout", models.DateField(max_length=10)),
                ("adults", models.IntegerField(max_length=10)),
                ("children", models.IntegerField(max_length=10)),
                ("note", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
