# Generated by Django 5.0.1 on 2024-01-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="adults",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="children",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.BigIntegerField(),
        ),
    ]
