# Generated by Django 5.0.1 on 2024-01-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddy", "0005_remove_booking_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="note",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
