# Generated by Django 5.0.1 on 2024-01-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buddy", "0007_alter_booking_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="note",
            new_name="utext",
        ),
    ]
