# Generated by Django 5.0.1 on 2024-01-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buddy", "0008_rename_note_booking_utext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="utext",
        ),
    ]
